FILE=main

all:
	latexmk -pdf -g ${FILE}

clean:
	(\rm -rf *.aux  *.bbl  *.blg  *.dvi  *.fdb_latexmk  *.fls \
	         *.lof  *.log  *.lot  *.html \
	         *.nav  *.out  *.pdf  *.prv _region_.*\
	         *.snm  *.sta  *.toc  *.vrb  *xcp )

